# -*- coding: utf-8 -*-
"""speech to text Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWZqaONGU3CA5VDkeCUJgKl5ZyoJI39z
"""

!pip install -q transformers==4.35.2 sentence-transformers==2.2.2 faiss-cpu

text = """
Artificial Intelligence (AI) is a branch of computer science that focuses on building intelligent systems.

Machine Learning is a subset of AI that allows systems to learn from data without explicit programming.

Natural Language Processing (NLP) helps machines understand human language.

Deep Learning uses neural networks to solve complex problems.

RAG (Retrieval-Augmented Generation) combines retrieval and generation techniques.

FAISS is a vector database used for similarity search.

Embeddings convert text into numerical format.

AWS is used for deploying scalable machine learning applications.
"""

with open("data.txt", "w") as f:
    f.write(text)

print("data.txt created successfully")

from sentence_transformers import SentenceTransformer
from transformers import pipeline

model = SentenceTransformer('all-MiniLM-L6-v2')

generator = pipeline("text2text-generation", model="google/flan-t5-base")

print("Setup working")

loader = TextLoader("data.txt")
documents = loader.load()

text_splitter = CharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=50
)

docs = text_splitter.split_documents(documents)

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vectorstore = FAISS.from_documents(docs, embeddings)

from transformers import pipeline

generator = pipeline(
    "text2text-generation",
    model="google/flan-t5-base",
    max_new_tokens=100
)

def rag_chatbot(query):

    retrieved_docs = vectorstore.similarity_search(query, k=2)

    context = ""
    for doc in retrieved_docs:
        context += doc.page_content + "\n"

    prompt = f"""
    Answer the question based on the context.

    Context:
    {context}

    Question:
    {query}
    """

    result = generator(prompt)

    return result[0]['generated_text']

print(rag_chatbot("What is RAG?"))

# =========================
# 1. INSTALL
# =========================
!pip install -q langchain langchain-community langchain-huggingface langchain-text-splitters faiss-cpu sentence-transformers transformers==4.36.2


# =========================
# 2. IMPORTS
# =========================
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from transformers import pipeline


# =========================
# 3. CREATE DATA FILE
# =========================
text = """
Artificial Intelligence (AI) is a branch of computer science.

Machine Learning is a subset of AI.

RAG (Retrieval-Augmented Generation) combines retrieval and generation techniques.

FAISS is used for similarity search.

Embeddings convert text into numbers.

AWS is used for deploying scalable applications.
"""

with open("data.txt", "w") as f:
    f.write(text)


# =========================
# 4. LOAD DATA
# =========================
loader = TextLoader("data.txt")
documents = loader.load()


# =========================
# 5. CHUNKING
# =========================
text_splitter = CharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=50
)

docs = text_splitter.split_documents(documents)


# =========================
# 6. EMBEDDINGS
# =========================
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)


# =========================
# 7. VECTOR STORE
# =========================
vectorstore = FAISS.from_documents(docs, embeddings)


# =========================
# 8. LLM
# =========================
generator = pipeline(
    "text2text-generation",
    model="google/flan-t5-base",
    max_new_tokens=100
)


# =========================
# 9. RAG FUNCTION
# =========================
def rag_chatbot(query):

    retrieved_docs = vectorstore.similarity_search(query, k=2)

    context = ""
    for doc in retrieved_docs:
        context += doc.page_content + "\n"

    prompt = f"""
    Answer the question based on the context.

    Context:
    {context}

    Question:
    {query}
    """

    result = generator(prompt)

    return result[0]['generated_text']


# =========================
# 10. TEST
# =========================
print(rag_chatbot("What is RAG?"))

